### ISSUE TITLE
preset: accepts a single value; would be great if it accepts an array too.

### ISSUE THREAD

**Issue by mvanbrab** [TiboStr/dataflow-visualization#132]
Example in the nodes:

Now:
```
   {
        "id": "thing1",
        "label": "thing 1",
        "preset": "generalThings",
        "fill": "green"
  }
```

Would be nice:
```
   {
        "id": "thing1",
        "label": "thing 1",
        "preset": ["generalThings", "coloredThings"]
  }
```

The expected behaviour would be:
1) load properties of "generalThings"
2) load properties of "coloredThings" (overrides properties with same name also present in "generalThings")
3) load local properties (overrides properties with same name in either preset

**Comment by TiboStr** [comment]
It will be slightly different. 

A preset won't just blindly overwrite stuff. If a key is already present and you load in a preset that has that key as well, the original key-value (so NOT the one in the preset) is used.

So the order of 'parsing':
1) Load in local properties.
2) Load in presets: if a key is not present yet, copy the key-value from the preset into the individual node/edge.
3) Load general properties

So the priority: local > preset > global default



An example: 

```json
{
    "graph": {},
    "node": {
        "fill": "yellow",
        "shape": "circle",
        "topText": "star",
        "presets": {
            "preset1": {
                "fill": "blue",
                "shape": "8-star"
            },
            "preset2": {
                "strokeDasharray": "dashed",
                "fill": "green",
                "shape": "square"
            }
        }
    },
    "edge": {}
}
```

```json
[
    {
        "preset": [
            "preset1",
            "preset2"
        ],
        "fill": "red"
    }
]
```

This config results in this:

![Screenshot_20220901_103746](https://user-images.githubusercontent.com/71405687/187870776-24613b8c-a8ce-4050-92cb-e3a0a7f003de.png)


### Why is  `fill` `red`?
Local properties have highest priority, so `fill` is `red`.

### Why is `shape` `8-star`?
After the local properties, the presets are loaded. So first we load in `preset1`. We already have a `fill`, so this is ignored. We do not have a `shape` red. So the value of `preset1` is used.




 ----------------


When this issue is done, I will of course explain all this in README.

**Comment by TiboStr** [comment]
Bigger example (with edges):

```json
{
    "graph": {},
    "node": {
        "fill": "yellow",
        "shape": "circle",
        "topText": "star",
        "presets": {
            "preset1": {
                "fill": "blue",
                "shape": "8-star"
            },
            "preset2": {
                "strokeDasharray": "dashed",
                "fill": "green",
                "shape": "square"
            }
        }
    },
    "edge": {
        "type": "smoothstep",
        "presets" : {
            "preset1": {
                "strokeDasharray": "dashed",
                "animation": "default"
            },
            "preset2" : {
                "strokeDasharray": "dotted",
                "label": "label"
            }
        }
    }
}
```

```json
[
    {
        "id": "1",
        "preset": [
            "preset1",
            "preset2"
        ],
        "fill": "red",
        "position": {
            "x": 45,
            "y": -90
        }
    },
    {
        "id": "2",
        "position": {
            "x": -60,
            "y": 15
        }
    }
]
```


```json
[
    {
        "type": "straight",
        "source": "1",
        "target": "2"
    }
]
```


Results in:

![Screenshot_20220901_110113](https://user-images.githubusercontent.com/71405687/187875613-529126d9-0c92-4e6a-8950-32d9798e21af.png)

**Comment by mvanbrab** [comment]
So shape is not square, because first preset wins; priority is: local > preset1 > preset2 > global.
I would have expected shape square, priority: local > preset2 > preset1 > global.
But if you document this clearly, I can live with your choice.

**Comment by mvanbrab** [comment]
Worth to mention: the current solution only accepts arrays now (even vor single elements), so all earlier exports are invalid now. Couldn't the word "also" from my original request be interpreted, meaning this property can be a single string or an array of strings?

**Comment by bjdmeest** [comment]
> Worth to mention: the current solution only accepts arrays now (even vor single elements), so all earlier exports are invalid now. Couldn't the word "also" from my original request be interpreted, meaning this property can be a single string or an array of strings?

+1000

@TiboStr make sure you don't break existing configs without warning :)
