### ISSUE TITLE
Global graph settings: autoLayout

### ISSUE THREAD

**Issue by bjdmeest** [TiboStr/dataflow-visualization#3]
change to `layout`, with setting 'default'/'horizontal'/'vertical'. Remove `orientation` (which doesn't do anything if autolayout is set to false?) Add an entry to DEVELOPMENT.md about where the layout is implemented and how to create a new layouting algorithm

**Comment by TiboStr** [comment]
The default value of `orientation` is `"horizontal"`. Change in example 3 the `orientation` to vertical. This is the result:
 
![Screenshot_20220804_170814](https://user-images.githubusercontent.com/71405687/182882027-424033b0-dc59-414a-9a0f-6346b238c356.png)


The reason why the connections are different is because `sourceHandle` and `targetHandle` are not defined. So in a `vertical` layout, it makes sense to connect the nodes at the top and the bottom, if the nodes are below each other.

The algorithm can be found here: https://github.com/TiboStr/dataflow-visualization/blob/d11452d3830081d567eab88cbbcd59145642b8bb/src/custom/editors/editorUtil.js#L319-L374

The idea is very simple. 

* If the layout is vertical,
    * Check if the nodes are on top/below each other
        * If so, the connections are the top/bottom
        * If not so, the connections should be at the side.
* Else if the layout is horizontal (default):
    * Check if the nodes are adjacent
        * If so, the connections are left/right
        * If not so the connections should be top/bottom

**Comment by bjdmeest** [comment]
Ah yeah, I didn't realize that 'orientation' is also relevant when 'autoLayout' is set to false, OK!
